"""Remove message nonce

Revision ID: 3af490431713
Revises: b844a7ec896e
Create Date: 2026-08-08 21:57:40.082630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3af490431713'
down_revision: Union[str, Sequence[str], None] = 'b844a7ec896e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'nonce')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('nonce', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
