"""Add conversation inactive status

Revision ID: fadcc1281b1c
Revises: 3af490431713
Create Date: 2026-08-08 22:53:05.344265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fadcc1281b1c'
down_revision: Union[str, Sequence[str], None] = '3af490431713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('inactive_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'inactive_at')
    # ### end Alembic commands ###
